# -*- coding: utf-8 -*-
"""Colored Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14OSXxtlhfnfG94Sm6YU_MuA4ZKQruAhR
"""

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
obb=KMeans(100)
img=(Image.open('Ronn.jpg'))                          
img_arr=np.array(img)                                               
plt.figure()
plt.imshow(img_arr)
plt.show()
img_data=np.reshape(img_arr,(168*300,3))                               
x=img_data  
obb.fit(x)        
center= obb.cluster_centers_
label = np.reshape(obb.labels_,(168,300))
plt.imshow(center[label].reshape(168,300,3).astype('uint8'))
plt.show()